package com.cxc.api.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "R_CLIENTES_MOVIMIENTOS", schema = "RADM")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ClienteMovimientos {

    @Id
    @Column(name = "ID_MOVIMIENTO", nullable = false)
    private Long idMovimiento;

    @Column(name = "IMPORTE")
    private BigDecimal importe;
    @Column(name = "FECHA")
    private Date fecha;
    @Column(name = "CALENDARIO")
    private Integer calendario;
    @Column(name = "TIPO_RECIBO")
    private String tipoRecibo;
    @Column(name = "NUM_FOLIO")
    private Long numFolio;
    @Column(name = "ID_COMPANIA", nullable = false)
    private Long idCompania;
    @Column(name = "IMPORTE_TOTAL")
    private BigDecimal importeTotal;
    @Column(name = "AUTORIZADO")
    private String autorizado;
    @Column(name = "NUM_FOLIO_FE")
    private String numFolioFe;
    @Column(name = "NOM_PDF")
    private String nomPdf;
    @Column(name = "NOM_XML")
    private String nomXml;
    @Column(name = "CANCELADA")
    private String cancelada;
    @Column(name = "OBSERVACION")
    private String observacion;
    @Column(name = "ID_CLIENTE")
    private Long idCliente;
    @Column(name = "ID_LOCAL")
    private Long idLocal;
    @Column(name = "SEC")
    private Long sec;
    @Column(name = "ID_CONCEPTO")
    private Long idConcepto;
    @Column(name = "METODO_PAGO")
    private String metodoPago;
    @Column(name = "NO_CUENTA_BANCO")
    private String noCuentaBanco;
    @Column(name = "ID_MONEDA")
    private Long idMoneda;
    @Column(name = "OBSERVACIONES")
    private String observaciones;
    @Column(name = "CLASIFICACION")
    private String clasificacion;
    @Column(name = "CANTIDAD")
    private BigDecimal cantidad;
    @Column(name = "TIPO_CAMBIO")
    private BigDecimal tipoCambio;
    @Column(name = "FECHA_CAP")
    private Date fechaCap;
    @Column(name = "NUM_FOLIO_FACTURA_NC")
    private Long numFolioFacturaNc;
    @Column(name = "NUM_FOLIO_FE_FACTURA_NC")
    private String numFolioFeFacturaNc;
    @Column(name = "TIPO_INGRESO")
    private String tipoIngreso;
    @Column(name = "CTO_COSTOS")
    private String ctoCostos;
    @Column(name = "BANCO_PAGO")
    private String bancoPago;
    @Column(name = "CUENTA_BANCO_PAGO")
    private String cuentaBancoPago;
    @Column(name = "FECHA_CANCELACION")
    private Date fechaCancelacion;
    @Column(name = "PAGO_TOTAL")
    private String pagoTotal;
    @Column(name = "IVA")
    private BigDecimal iva;
    @Column(name = "RET_IVA")
    private BigDecimal retIva;
    @Column(name = "RET_ISR")
    private BigDecimal retIsr;
    @Column(name = "UNIDAD")
    private String unidad;
    @Column(name = "DIAS_REVISION")
    private Integer diasRevision;
    @Column(name = "FECHA_REVISION")
    private Date fechaRevision;
    @Column(name = "NOTAS")
    private String notas;
    @Column(name = "EXENTO")
    private String exento;
    @Column(name = "METODOPAGO_SAT")
    private String metodopagoSat;
    @Column(name = "FORMAPAGO_SAT")
    private String formapagoSat;
    @Column(name = "USOCFDI_SAT")
    private String usocfdiSat;
    @Column(name = "CLAVEPROD_SAT")
    private String claveprodSat;
    @Column(name = "CLAVEUNIDAD_SAT")
    private String claveunidadSat;
    @Column(name = "IEPS")
    private BigDecimal ieps;
    @Column(name = "RET_IEPS")
    private BigDecimal retIeps;
    @Column(name = "TRASLADOS")
    private BigDecimal traslados;
    @Column(name = "RETENCIONES")
    private BigDecimal retenciones;
    @Column(name = "FORMADEPAGOP")
    private String formadepagop;
    @Column(name = "NUMOPERACION")
    private String numoperacion;
    @Column(name = "RFCEMISORCATORD")
    private String rfcemisorcatord;
    @Column(name = "NOMBANCOORDEXT")
    private String nombancoordext;
    @Column(name = "CTAORDENANTE")
    private String ctaordenante;
    @Column(name = "TIPOCADPAGO")
    private String tipocadpago;
    @Column(name = "CERTPAGO")
    private String certpago;
    @Column(name = "CADPAGO")
    private String cadpago;
    @Column(name = "SELLOPAGO")
    private String sellopago;
    @Column(name = "NUMPARCIALIDAD")
    private Long numparcialidad;
    @Column(name = "IMPSALDOANT")
    private BigDecimal impsaldoant;
    @Column(name = "CFDI_PAGO")
    private String cfdiPago;
    @Column(name = "NUM_FOLIO_FE_PAGO")
    private String numFolioFePago;
    @Column(name = "UUID_PAGO")
    private String uuidPago;
    @Column(name = "DESCUENTO")
    private BigDecimal descuento;
    @Column(name = "UUID")
    private String uuid;
    @Column(name = "SECC")
    private Long secc;
    @Column(name = "HORA")
    private String hora;
    @Column(name = "SECUENCIAL")
    private Long secuencial;
    @Column(name = "NOIDENTIFICACION")
    private String noidentificacion;
    @Column(name = "IVA_PORC")
    private BigDecimal ivaPorc;
    @Column(name = "RET_IVA_PORC")
    private BigDecimal retIvaPorc;
    @Column(name = "IEPS_PORC")
    private BigDecimal iepsPorc;
    @Column(name = "RET_IEPS_PORC")
    private BigDecimal retIepsPorc;
    @Column(name = "RET_ISR_PORC")
    private BigDecimal retIsrPorc;
    @Column(name = "FOLIO_PREFACTURA")
    private Long folioPrefactura;
    @Column(name = "USUARIO_CAPTURO")
    private String usuarioCapturo;
    @Column(name = "USUARIO_TIMBRO")
    private String usuarioTimbro;
    @Column(name = "ID_LUGAR_EXPEDICION")
    private Long idLugarExpedicion;
    @Column(name = "TIPO_CAMBIO_PAGO")
    private BigDecimal tipoCambioPago;
    @Column(name = "SERIE")
    private String serie;
    @Column(name = "HORA_AGRUPACION_PAGOS")
    private String horaAgrupacionPagos;
    @Column(name = "MONEDA_PAGO")
    private String monedaPago;
    @Column(name = "NUMERO_PEDIMENTO")
    private String numeroPedimento;
    @Column(name = "TIPO_RELACION_PAGO")
    private String tipoRelacionPago;
    @Column(name = "UUID_RELACION_PAGO")
    private String uuidRelacionPago;
    @Column(name = "NUM_ORDEN_COMPRA")
    private String numOrdenCompra;
    @Column(name = "FECHA_SOL_CANCELA")
    private Date fechaSolCancela;
    @Column(name = "ESTATUS_CANCELACION")
    private String estatusCancelacion;
    @Column(name = "COTIZACION")
    private String cotizacion;
    @Column(name = "AGRUPACION_PAGOS")
    private String agrupacionPagos;
    @Column(name = "ID_ANTICIPO")
    private Long idAnticipo;
    @Column(name = "CONDICIONES_PAGO")
    private String condicionesPago;
    @Column(name = "DATOS_SK_ORIGEN")
    private String datosSkOrigen;
    @Column(name = "DATOS_SK_LUGAR")
    private String datosSkLugar;
    @Column(name = "DATOS_SK_PERIODO")
    private String datosSkPeriodo;
    @Column(name = "FECHA_REP")
    private Date fechaRep;
    @Column(name = "FECHA_TIMBRADO_PAGO")
    private Date fechaTimbradoPago;
    @Column(name = "CUENTA_INGRESO")
    private String cuentaIngreso;
    @Column(name = "CUENTA_CXC")
    private String cuentaCxc;
    @Column(name = "CUENTA_CXC_COMPLEMENTARIA")
    private String cuentaCxcComplementaria;
    @Column(name = "USUARIO_CANCELA")
    private String usuarioCancela;
    @Column(name = "ID_PLANTA")
    private Long idPlanta;
    @Column(name = "ID_DEPOSITO_SIN")
    private Long idDepositoSin;
    @Column(name = "TIPO_CAMBIO_PAGO_ESPECIAL")
    private BigDecimal tipoCambioPagoEspecial;
    @Column(name = "MOTIVO_CANCELACION")
    private String motivoCancelacion;
    @Column(name = "MOTIVO_SUSTITUCION")
    private String motivoSustitucion;
    @Column(name = "MOTIVO_NC")
    private String motivoNc;
    @Column(name = "CM")
    private BigDecimal cm;
    @Column(name = "COSTOXCM")
    private BigDecimal costoxcm;
    @Column(name = "FECHA_VENCIMIENTO")
    private Date fechaVencimiento;
    @Column(name = "NUM_FOLIO_FACTURA_ND")
    private Long numFolioFacturaNd;
    @Column(name = "NUM_FOLIO_FE_FACTURA_ND")
    private String numFolioFeFacturaNd;
    @Column(name = "MOTIVO_CANCELACION_SAT")
    private String motivoCancelacionSat;
    @Column(name = "FOLIO_FISCAL_SAT")
    private String folioFiscalSat;
    @Column(name = "CFDI_PAGO_CANCELADO_VIRTUAL")
    private String cfdiPagoCanceladoVirtual;
    @Column(name = "CFDI_PAGO_CANCELADO_VIRTUAL_FECHA")
    private Date cfdiPagoCanceladoVirtualFecha;
    @Column(name = "EXPORTACION")
    private String exportacion;
    @Column(name = "PERIODICIDAD")
    private String periodicidad;
    @Column(name = "MESES")
    private String meses;
    @Column(name = "ANIO")
    private String anio;
    @Column(name = "VERSION")
    private String version;
    @Column(name = "OBJETOIMP")
    private String objetoimp;
    @Column(name = "RFCACUENTATERCEROS")
    private String rfcacuentaterceros;
    @Column(name = "NOMBREACUENTATERCEROS")
    private String nombreacuentaterceros;
    @Column(name = "REGIMENFISCALACUENTATERCEROS")
    private String regimenfiscalacuentaterceros;
    @Column(name = "DOMICILIOFISCALACUENTATERCEROS")
    private String domiciliofiscalacuentaterceros;
    @Column(name = "OBJETOIMPDR")
    private String objetoimpdr;
    @Column(name = "FECHA_AUTORIZADO")
    private Date fechaAutorizado;
}
